### ISSUE TITLE
Set REMOTE_LIST_CACHEDIR to /var/cache/eselect-repo

### ISSUE THREAD

**Issue by crocket** [projg2/eselect-repository#11]
Because REMOTE_LIST_CACHEDIR is set to ~/.cache/eselect-repo by default, I thought I could add overlays as a normal user. I couldn't.

Having a single location for the cache is less confusing.

**Comment by mgorny** [comment]
You can add them as regular user, you just have to set appropriate permissions.

**Comment by crocket** [comment]
Using `~/.cache/eselect-repo` isn't beautiful.

**Comment by mgorny** [comment]
XDG spec disagrees.

**Comment by crocket** [comment]
What I mean is that eselect-repo is a system thing. It doesn't differ according to each user.
