### ISSUE TITLE
eselect-repository should have a git USE flag

### ISSUE THREAD

**Issue by SigHunter** [projg2/eselect-repository#17]
Most (or at least many) user repositories use git to sync the repository data. 
However, app-eselect/eselect-repository does not pull in dev-vcs/git and therefore repositories using git do not work. 

One has to manually emerge dev-vcs/git (and therefore add it to /var/lib/portage/world), which feels wrong because this is not a "user desired" application but more of a dependency. 

app-portage/layman which basically does the same thing as eselect-repository and is it's predecessor (in spirit?) has USE=git and it is enabled by default. This is in my opinion how it should be handled

Currently, I only care about git but other source code version control systems (like subversion or cvs) could be implemented with their use flags as well, to pull in the necessary dependencies

Regards

**Comment by Kangie** [comment]
`USE=git` to add what amounts to an `optfeature` is not reasonable. Sorry.

**Comment by SigHunter** [comment]
Very happy this was not so unreasonable after all :-) 
https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=141153ee9444becebe8b512ef043e258436e8ab5
I'll therefore close this. The right place probably also would've been the gentoo bug tracker, as it was a packaging issue
