### ISSUE TITLE
Allow invocation via `eselect repo` in addition to `eselect repository` 

### ISSUE THREAD

**Issue by maffblaster** [projg2/eselect-repository#24]
I find myself trying to use this short hand version of invocation, even though it does not presently exist. Please allow invocation via a shortened `eselect repo` in addition to the full `eselect repository` command.

Thank you!

**Comment by mgorny** [comment]
To the best of my knowledge, the code doesn't care about the name. This is an ebuild problem. However, I'm not aware of any precedence of allowing two names for eselect modules, and I don't see why this one would be a first.
