### ISSUE TITLE
TypeError: strxfrm() argument 1 must be str, not None

### ISSUE THREAD

**Issue by MeisterP** [projg2/eselect-repository#3]
I get the following error with the list command:

```
eselect repository list 
Available repositories:
Traceback (most recent call last):
  File "/usr/lib/eselect-repo/eselect-repo-helper", line 145, in <module>
    main()
  File "/usr/lib/eselect-repo/eselect-repo-helper", line 135, in main
    do_list(args)
  File "/usr/lib/eselect-repo/eselect-repo-helper", line 37, in do_list
    key=lambda x: locale.strxfrm(x.findtext('name'))):
  File "/usr/lib/eselect-repo/eselect-repo-helper", line 37, in <lambda>
    key=lambda x: locale.strxfrm(x.findtext('name'))):
TypeError: strxfrm() argument 1 must be str, not None
!!! Error: helper failed to run
exiting
```

[emerge-info.txt](https://github.com/mgorny/eselect-repository/files/1841053/emerge-info.txt)
[repository.conf.txt](https://github.com/mgorny/eselect-repository/files/1841061/repository.conf.txt)

**Comment by mgorny** [comment]
Looks like it doesn't handle comments well. Will fix in a minute.

**Comment by mgorny** [comment]
If you could test -9999 and confirm it's fixed, I'll appreciate. I'll make a release later today.

**Comment by MeisterP** [comment]
Yes, it's working fine with `app-eselect/eselect-repository-9999` indeed.
