### ISSUE TITLE
Enhancement: Make it possible to create a per repo file in repos.conf

### ISSUE THREAD

**Issue by gerion0** [projg2/eselect-repository#4]
There is the `REPOS_CONF_SUBFILE` variable, where the file can be defined, where new repos are placed, if repos.conf is a directory.

My workflow was to add one file per repo. It would be nice if you adjust the script, so that one can specify this variable on a per repo basis, e.g. introduce a variable: `REPO_NAME` so that `REPOS_CONF_SUBFILE` can be defined as:
```
REPOS_CONF_SUBFILE=${REPOS_CONF}/${REPO_NAME}.conf
```
that would result with e.g.:
```
eselect repository enable kde
```
in
```
REPOS_CONF_SUBFILE=/etc/portage/repos.conf/kde.conf
```

**Comment by mgorny** [comment]
Shouldn't be hard to implement. I'll try to do it in a minute.

**Comment by mgorny** [comment]
Ok, not that simple. The current logic combines all updates into one operations, so I'd need to split that first.

**Comment by mgorny** [comment]
Now in v4.

**Comment by mgorny** [comment]
(I'm sorry, I've just noticed I've got checkout dirty and haven't finished the PR review from the morning, so it will take a few more minutes before I push it to ::gentoo)

**Comment by gerion0** [comment]
Nice, thank you!
